// Code generated by "stringer -type=kind"; DO NOT EDIT.

package less

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[space-0]
	_ = x[tokenNewline-1]
	_ = x[tokenAt-2]
	_ = x[tokenBackslash-3]
	_ = x[tokenBracketClose-4]
	_ = x[tokenBracketOpen-5]
	_ = x[tokenColon-6]
	_ = x[tokenCurlyClose-7]
	_ = x[tokenCurlyOpen-8]
	_ = x[tokenDot-9]
	_ = x[tokenExclamation-10]
	_ = x[tokenGt-11]
	_ = x[tokenHash-12]
	_ = x[tokenIdentifier-13]
	_ = x[tokenPercent-14]
	_ = x[tokenLt-15]
	_ = x[tokenMinus-16]
	_ = x[tokenUnderscore-17]
	_ = x[tokenParensClose-18]
	_ = x[tokenParensOpen-19]
	_ = x[tokenPlus-20]
	_ = x[tokenQuestion-21]
	_ = x[tokenComma-22]
	_ = x[tokenSemi-23]
	_ = x[tokenSlash-24]
	_ = x[tokenStar-25]
	_ = x[tokenEq-26]
	_ = x[tokenNum-27]
	_ = x[tokenSingleQuote-28]
	_ = x[tokenDoubleQuote-29]
	_ = x[tokenTilde-30]
	_ = x[compGt-31]
	_ = x[compGte-32]
	_ = x[compLt-33]
	_ = x[compLte-34]
	_ = x[compEq-35]
	_ = x[compNEq-36]
}

const _kind_name = "spacetokenNewlinetokenAttokenBackslashtokenBracketClosetokenBracketOpentokenColontokenCurlyClosetokenCurlyOpentokenDottokenExclamationtokenGttokenHashtokenIdentifiertokenPercenttokenLttokenMinustokenUnderscoretokenParensClosetokenParensOpentokenPlustokenQuestiontokenCommatokenSemitokenSlashtokenStartokenEqtokenNumtokenSingleQuotetokenDoubleQuotetokenTildecompGtcompGtecompLtcompLtecompEqcompNEq"

var _kind_index = [...]uint16{0, 5, 17, 24, 38, 55, 71, 81, 96, 110, 118, 134, 141, 150, 165, 177, 184, 194, 209, 225, 240, 249, 262, 272, 281, 291, 300, 307, 315, 331, 347, 357, 363, 370, 376, 383, 389, 396}

func (i kind) String() string {
	if i < 0 || i >= kind(len(_kind_index)-1) {
		return "kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _kind_name[_kind_index[i]:_kind_index[i+1]]
}
